### ISSUE TITLE
使用kotlin开发现在必须使用android studio的3.0 预览版本吗?

### ISSUE THREAD

**Issue by vipzrx** [Gh0u1L5/WechatMagician#10]
现在电脑上安装了2.3.3的稳定版本 和3.0的预览版. 虽然这两个版本可以共存,但是会共享一些设置目录,同时有的时候会将一个版本的设置,错误的设置到另一个版本配置文件中?
1 稳定版本还是不支持kotlin吗? 使用一些插件也不行吗?

**Comment by vipzrx** [comment]
两个版本使用的程序是一样的, 只是配置文件存放在不同的地方
![20171014_155009](https://user-images.githubusercontent.com/5094958/31573938-ac77c0b6-b0f7-11e7-8d13-2d039ac0e84d.png)

**Comment by Gh0u1L5** [comment]
稳定版本支持Kotlin的，我一开始用的就是稳定版本，后来为了尝鲜才换了预览版。我记得只要在设置界面搜索安装Kotlin的插件就好了。

**Comment by stlyx** [comment]
这个 Gradle 的语法好像得 Android Studio 3+ 才支持。
