### ISSUE TITLE
 Could not resolve com.android.tools.build:gradle:3.0.0-beta7.

### ISSUE THREAD

**Issue by vipzrx** [Gh0u1L5/WechatMagician#11]
从github上clone代码, 导入as中, gradle sync失败

build log 如下:

Information:Gradle tasks [clean]
Error:A problem occurred configuring root project 'Gh0u1L5-WechatMagician'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.0.0-beta7.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.0.0-beta7.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.0-beta7/gradle-3.0.0-beta7.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.0-beta7/gradle-3.0.0-beta7.pom'.
               > Connect to dl.google.com:443 [dl.google.com/203.208.51.69, dl.google.com/203.208.51.68, dl.google.com/203.208.51.64, dl.google.com/203.208.51.71, dl.google.com/203.208.51.78, dl.google.com/203.208.51.66, dl.google.com/203.208.51.73, dl.google.com/203.208.51.72, dl.google.com/203.208.51.65, dl.google.com/203.208.51.70, dl.google.com/203.208.51.67] failed: Connection timed out: connect
Information:BUILD FAILED in 3m 54s
Information:1 error
Information:0 warnings
Information:See complete output in console

我看到你的项目中

gradle/wrapper/gradle-wrapper.properties 中 用的是gradle 4.1

distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

但是
build.gradle 中

buildscript {
    ext.kotlin_version = '1.1.51'
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-beta7'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
用的是 gradle:3.0.0-beta7

在我的电脑上, 启动的时候已经将gradle 4.1下载到本地
{ dists }  » tree -L 4                                 /cygdrive/c/Users/kk/.gradle/wrapper/dists
.
└── gradle-4.1-all
    └── bzyivzo6n839fup2jbap0tjew
        ├── gradle-4.1
        │   ├── bin
        │   ├── docs
        │   ├── getting-started.html
        │   ├── init.d
        │   ├── lib
        │   ├── LICENSE
        │   ├── media
        │   ├── NOTICE
        │   ├── samples
        │   └── src
        ├── gradle-4.1-all.zip
        ├── gradle-4.1-all.zip.lck
        └── gradle-4.1-all.zip.ok

10 directories, 6 files

**Comment by vipzrx** [comment]
https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.0-beta7/gradle-3.0.0-beta7.pom 输入到浏览器中 也是失效

**Comment by Gh0u1L5** [comment]
Ummm，只看日志的话感觉单纯是被墙了或者服务器出了点问题，另外zip的版本4.1-all应该是wrapper的版本，而插件版本是3.0.0-beta7，这些都是Android Studio自动配置的，应该没什么问题。
