### ISSUE TITLE
hi :)

### ISSUE THREAD

**Issue by LeeLejia** [Gh0u1L5/WechatMagician#12]
请问在开发插件的时候可以使用什么工具呢？有没有比较好的方法呢.:-)

**Comment by Gh0u1L5** [comment]
@cjwddz Ummm，我开发插件主要就是用Android Studio的开发环境，用apktool做逆向工具，然后用atom配合smali的插件直接读smali源码，因为大多数smali转Java的逆向工具都会把原本的逻辑逆向地乱七八糟。除此之外，善用smali源码里出现的各种字符串，因为目前来看字符串是不会被混淆打乱的。

**Comment by LeeLejia** [comment]
谢谢！
