### ISSUE TITLE
微信6.5.8 ClassNotFoundException

### ISSUE THREAD

**Issue by holymonk** [Gh0u1L5/WechatMagician#15]
您好，我下载了代码自己编译后运行时出错了，错误信息如下
>de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.storage.aa

**Comment by Gh0u1L5** [comment]
Ummm，解决了？

**Comment by holymonk** [comment]
解决了，没找到的类直接跳过不管了。
