### ISSUE TITLE
撤回图片无法显示

### ISSUE THREAD

**Issue by pkqxdd** [Gh0u1L5/WechatMagician#2]
现在在微信里，当有人撤回图片时，没有任何标记或提示表明这个图片被撤回了。

**Comment by crimx** [comment]
嗯嗯，不知可不可以实现像原来的“xxx撤回了一条消息”一样的通知。这样无论文字或者图片都可以知道被撤回。

**Comment by Gh0u1L5** [comment]
我觉得你们说的很有道理，容我研究研究

**Comment by Gh0u1L5** [comment]
@pkqxdd @crimx 在刚刚更新的2.0.0版里实现了这个功能，这个issue我先关了昂。

**Comment by crimx** [comment]
@Gh0u1L5 真是太棒了！ :heart: 马上升级了发现个 bug，图片需要点开完全加载的才会变成撤回的图片，如果没有点过缩略图的没有反应。

还有，我上面提到的意思其实是图片这样，像这样的不知道实现起来麻烦不，能不能用调用微信的方法。

![example](https://user-images.githubusercontent.com/6882794/30373045-988607a0-98b2-11e7-9c00-d3ffed0d5dc6.png)

**Comment by Gh0u1L5** [comment]
@crimx 
唔，不应该啊，你试试撤回之后不点它，多等一段时间？在我本机测试的时候不用点开略缩图也能完成替换的。
我最早接触的防撤回插件用的也是这种格式，这个倒不是不行，但是我觉得这个效果不太好玩。不过以后撤回名片啊、自定义表情啊，可以考虑试试这个。

**Comment by crimx** [comment]
@Gh0u1L5 嗯对，等一会就行了，可能我刚好在这期间点开了。我上面只是从常规交互角度想，现在的实现确实比较新颖哈哈。
