### ISSUE TITLE
插件未能加载，请检查xp框架 其他插件都没有问题

### ISSUE THREAD

**Issue by xiiaomiku** [Gh0u1L5/WechatMagician#23]
组件运行状态全都打叉 用的是xda的xp框架
Cannot read log/data/user_de/0/de.robv.android.xposed.installer/log/error.log (No such file or directory) 这个是xda日志

**Comment by xiiaomiku** [comment]
已解决

**Comment by Gh0u1L5** [comment]
Ummm，好的，那我关了？

**Comment by xiiaomiku** [comment]
好的

**Comment by Alwayslazydog** [comment]
怎么解决的呀

**Comment by xiiaomiku** [comment]
试看其他的版本 可是我目前没办法试了 我现在用iPhone了

Alwayslazydog <notifications@github.com> 于2018年8月30日周四 下午2:55写道：
