### ISSUE TITLE
长按朋友圈屏幕没空间显示菜单时微信崩溃

### ISSUE THREAD

**Issue by stlyx** [Gh0u1L5/WechatMagician#27]
When long press on SNS moment, if current screen has no space to render menu (i.e. the selected SNS moment top higher than action bar, bottom lower than screen bottom), the WeChat app will crash. 
This can be solved by manually scrolling to somewhere with space to show the menu, no affects on functionality but only bad experience if long tap by mistake caused crash.

**Comment by Gh0u1L5** [comment]
Ummmm, this bug sounds interesting, I'd like to spend some time fixing it.

**Comment by Gh0u1L5** [comment]
Fixed in new version v2.6.0
