### ISSUE TITLE
【bug】360N5 微信 6.5.13 版本测试失败

### ISSUE THREAD

**Issue by dkvirus** [Gh0u1L5/WechatMagician#3]
- 对这个项目挺感兴趣的，感觉也挺使用的，就是没有移动端开发经验，不太懂怎么使用。

- 安装包 .apk 也下载并安装了，但是测试并没有效果。

- 手机：360N5。微信版本：6.5.13

- 如果能写一份使用文档放到 README.md 中，肯定会为项目带来更多粉丝的。

**Comment by Gh0u1L5** [comment]
你好，感谢反馈，
1. 这个项目是一个Xposed插件，需要Xposed框架的支持。
2. 目前计划是有时间的话在主界面增加一些检查环境和引导用户的提示。
3. 这个项目的编译器是Android Studio Preview版，用它可以直接打开项目。

**Comment by Gh0u1L5** [comment]
长时间无回复，暂时关闭。
