### ISSUE TITLE
新功能提议:屏蔽微信的强制新版本更新弹窗提醒

### ISSUE THREAD

**Issue by zeusro** [Gh0u1L5/WechatMagician#35]
我们都知道这种应用跟微信版本是高度耦合的,应用适配微信最新版必然需要一个过程.在这个时间段内,微信反复提醒用户升级应用,让用户很烦恼(本人也深受其扰)

所以我建议如果这个功能如果实现难度不大的话,能否考虑在以后版本里面加入这项功能

**Comment by Gh0u1L5** [comment]
可以倒是可以，但是巫师跟微信版本并不是高度耦合的，从6.5.8至现在6.6.1为止，所有的微信更新都成功通过算法自动适配，没有一例因为微信版本更新而导致功能失效的情况，之后的微信更新应该也大概率能直接成功。
