### ISSUE TITLE
[BUG] 版本2.7.1

### ISSUE THREAD

**Issue by vlt23** [Gh0u1L5/WechatMagician#37]
你好。

在微信巫师 版本 2.7.1 中，当我打开某个图片的时候，会造成微信直接闪退。
我用CatLog看了一下tencent，发现了一个exception（不知道是不是造成微信闪退的原因）。

另外 ，根据巫师changelog，好像对图片视频撤回进行了BUG修改，但是我在使用2.7.0当中并没有任何的问题（图片视频对方撤回了，我还是打得开）。
在使用2.7.0的时候，CatLog里就没有exception。

使用的微信版本：6.5.10
XPOSED: v89
Android 7.1

有什么地方可以提供资料的话，请说。谢谢！

![screenshot_20180201-125208](https://user-images.githubusercontent.com/32304181/35678021-1b8d12b6-0752-11e8-852f-c098504931f9.png)

**Comment by Gh0u1L5** [comment]
感谢反馈，我试着重现了一下，发现是自己昨晚更新的时候有个地方打错字了，详见https://github.com/Gh0u1L5/WechatMagician/commit/df719a04b12806b13047a62dbf4bb098505d649b

发布更新用的密钥锁在自己笔记本电脑里，所以只好等回家再发布2.7.2更新了。

**Comment by vlt23** [comment]
谢谢！

**Comment by youthlin** [comment]
同样的问题 2.7.2还没发布吗

**Comment by Gh0u1L5** [comment]
@YouthLin 发布了啊？现在酷安和Xposed官方库应该都能看到更新了
