### ISSUE TITLE
[BUG] 表情

### ISSUE THREAD

**Issue by vlt23** [Gh0u1L5/WechatMagician#4]
你好。

首先谢谢你开发这个插件。

我在使用2.1.1的版本，发现了BUG。经过我的测试发现以下BUG：
 -发表情的时候会一直显示在发送（转圈圈），但是对方收得到表情（表情是有发出去但是在本机上还是显示发送中）。
 -表情 撤回不了（我想可能是因为微信以为表情还没发出去有关）。

另外 提供一些想法：
 -当自己撤回消息的时候，消息会保留在本机上，但是希望添加一个提示什么的（因为有时候会怀疑有没有撤回） <--- 对于我来说并不重要，只是一个想法。

谢谢！

插件版本：2.1.1
XPOSED 版本： 87.3-sdk 25 Systemless by topjohnwu
微信版本：6.5.10

**Comment by Gh0u1L5** [comment]
@vlt23 非常感谢反馈，这个问题会在这周五之前修复的。

**Comment by vlt23** [comment]
非常感谢。
来个温馨提示... 看作者最近事情比较多，加上这个BUG不严重，作者不用很急的修好。就如作者的室友所说，好好休息！

**Comment by Gh0u1L5** [comment]
可以的，很感人，但是这个bug确实不大，已经修复了，会跟着之后转发朋友圈的新功能一起发布的

**Comment by Gh0u1L5** [comment]
@vlt23 已经在这周末发布的新版本里修复该bug。

**Comment by vlt23** [comment]
谢谢提醒。刚刚试了下，已经没任何问题了。再次谢谢！
