### ISSUE TITLE
关于语音消息对方撤回后无法听的问题

### ISSUE THREAD

**Issue by Wazy-XD** [Gh0u1L5/WechatMagician#42]
荣耀v9语音消息撤回后无法听，用使用抢红包插件，微信版本3.5.0

**Comment by Wazy-XD** [comment]
微信版本是6.6.3，我还安装了指纹支付的3.5.0XP框架模块，看错了

**Comment by Gh0u1L5** [comment]
多谢反馈，这个问题现在已经修复了 https://github.com/Gh0u1L5/WechatMagician/commit/9b6b49efaff855123f6b037a3abf10fbe1c5e878 ，预计下一个版本会得到修复。
