### ISSUE TITLE
建议提供app图标隐藏功能

### ISSUE THREAD

**Issue by zeusro** [Gh0u1L5/WechatMagician#5]
目前app应用内无设置项什么的,不大需要图标吧

**Comment by Gh0u1L5** [comment]
1. 主界面里面计划增加一些检查运行环境和Xposed状态的面板，到时候就会比较有用了
2. 其实我也想过隐藏图标的功能，但是我一时间没想到隐藏之后用户要怎么比较方便的找回来，所以这个功能我就先放放了。

**Comment by raidenii** [comment]
隐藏之后可以通过Xposed Installer->模块打开用户界面，都已经会用Xposed了这个不算复杂吧……

**Comment by Gh0u1L5** [comment]
哦惊了，我忘了这个操作了

**Comment by Gh0u1L5** [comment]
@zeusro @raidenii 新版本里面已经加入这个功能了，issue我先关了？
