### ISSUE TITLE
安卓5.1，微信6.5.13转发朋友圈功能没有反应

### ISSUE THREAD

**Issue by kuku982** [Gh0u1L5/WechatMagician#6]
我手机安卓5.1系统，微信6.5.13朋友圈的转发功能，点了没有任何反应！

**Comment by Gh0u1L5** [comment]
@kuku982 屏幕下方有浮出“请稍等片刻……”字样的悬浮提示吗？如果没有的话重启一次试试看？重启没效果的话麻烦贴一下Xposed的日志记录。

**Comment by kuku982** [comment]
没有，什么反应都没有，重启过很多次了

**Comment by kuku982** [comment]
10-02 21:16:19.849 I/Xposed  (  362): -----------------
10-02 21:16:19.849 I/Xposed  (  362): Starting Xposed version 87, compiled for SDK 22
10-02 21:16:19.849 I/Xposed  (  362): Device: m1 metal (Meizu), Android version 5.1 (SDK 22)
10-02 21:16:19.849 I/Xposed  (  362): ROM: Flyme 6.2.0.0A
10-02 21:16:19.849 I/Xposed  (  362): Build fingerprint: Meizu/meizu_m1metal/m1metal:5.1/LMY47I/1505901051:user/release-keys
10-02 21:16:19.849 I/Xposed  (  362): Platform: arm64-v8a, 64-bit binary, system server: yes
10-02 21:16:19.849 I/Xposed  (  362): SELinux enabled: yes, enforcing: no
10-02 21:16:22.855 I/Xposed  (  362): -----------------
10-02 21:16:22.856 I/Xposed  (  362): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-02 21:16:23.515 I/Xposed  (  362): Detected ART runtime
10-02 21:16:23.530 I/Xposed  (  362): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-02 21:16:23.885 I/Xposed  (  362): Loading modules from /data/app/com.oslorde.jrtthook-2/base.apk
10-02 21:16:23.892 I/Xposed  (  362):   Loading class com.oslorde.jrtthook.Hook
10-02 21:16:23.909 I/Xposed  (  362): Loading modules from /data/app/mrack.qqlive-1/base.apk
10-02 21:16:23.914 I/Xposed  (  362):   Loading class mrack.qqlive.mrack
10-02 21:16:23.916 I/Xposed  (  362): Loading modules from /data/app/com.fkzhang.wechatxposed-2/base.apk
10-02 21:16:23.928 I/Xposed  (  362):   Loading class com.fkzhang.wechatxposed.XposedInit
10-02 21:16:23.933 I/Xposed  (  362): Loading modules from /data/app/com.gh0u1l5.wechatmagician-2/base.apk
10-02 21:16:23.949 I/Xposed  (  362):   Loading class com.gh0u1l5.wechatmagician.xposed.WechatHook
10-02 21:16:24.010 I/Xposed  (  362): Loading modules from /data/app/moe.reimu.weiboxposed-1/base.apk
10-02 21:16:24.021 I/Xposed  (  362):   Loading class moe.reimu.weiboxposed.Module
10-02 21:16:24.046 I/Xposed  (  362): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.CLON-1/base.apk
10-02 21:16:24.064 I/Xposed  (  362):   Loading class com.chelpus.XSupport
10-02 21:16:24.090 I/Xposed  (  362): Loading modules from /data/app/com.phantom.onetapvideodownload-1/base.apk
10-02 21:16:24.110 I/Xposed  (  362):   Loading class com.phantom.onetapvideodownload.hooks.MediaPlayerHook
10-02 21:16:24.118 I/Xposed  (  362):   Loading class com.phantom.onetapvideodownload.hooks.SelfHook
10-02 21:16:24.123 I/Xposed  (  362):   Loading class com.phantom.onetapvideodownload.hooks.WebViewHook
10-02 21:16:24.124 I/Xposed  (  362):   Loading class com.phantom.onetapvideodownload.hooks.ChromeHook
10-02 21:16:24.125 I/Xposed  (  362):   Loading class com.phantom.onetapvideodownload.hooks.MediaMetadataRetriever
10-02 21:16:24.126 I/Xposed  (  362):   Loading class com.phantom.onetapvideodownload.hooks.SoundCloudHook
10-02 21:16:24.127 I/Xposed  (  362):   Loading class com.phantom.onetapyoutubemodule.YoutubeMediaHook
10-02 21:16:24.130 I/Xposed  (  362):   Loading class com.phantom.onetapfacebookmodule.FacebookHook
10-02 21:16:24.132 I/Xposed  (  362):   Loading class com.phantom.onetapfacebookmodule.FacebookLiteHook
10-02 21:16:29.292 I/Xposed  (  363): -----------------
10-02 21:16:29.293 I/Xposed  (  363): Starting Xposed version 87, compiled for SDK 22
10-02 21:16:29.293 I/Xposed  (  363): Device: m1 metal (Meizu), Android version 5.1 (SDK 22)
10-02 21:16:29.293 I/Xposed  (  363): ROM: Flyme 6.2.0.0A
10-02 21:16:29.293 I/Xposed  (  363): Build fingerprint: Meizu/meizu_m1metal/m1metal:5.1/LMY47I/1505901051:user/release-keys
10-02 21:16:29.293 I/Xposed  (  363): Platform: arm64-v8a, 32-bit binary, system server: no
10-02 21:16:29.293 I/Xposed  (  363): SELinux enabled: yes, enforcing: no
10-02 21:16:31.985 I/Xposed  (  363): -----------------
10-02 21:16:31.985 I/Xposed  (  363): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-02 21:16:32.490 I/Xposed  (  363): Detected ART runtime
10-02 21:16:32.506 I/Xposed  (  363): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-02 21:16:32.809 I/Xposed  (  363): Loading modules from /data/app/com.oslorde.jrtthook-2/base.apk
10-02 21:16:32.814 I/Xposed  (  363):   Loading class com.oslorde.jrtthook.Hook
10-02 21:16:32.816 I/Xposed  (  363): Loading modules from /data/app/mrack.qqlive-1/base.apk
10-02 21:16:32.820 I/Xposed  (  363):   Loading class mrack.qqlive.mrack
10-02 21:16:32.821 I/Xposed  (  363): Loading modules from /data/app/com.fkzhang.wechatxposed-2/base.apk
10-02 21:16:32.833 I/Xposed  (  363):   Loading class com.fkzhang.wechatxposed.XposedInit
10-02 21:16:32.840 I/Xposed  (  363): Loading modules from /data/app/com.gh0u1l5.wechatmagician-2/base.apk
10-02 21:16:35.805 I/Xposed  (  363):   Loading class com.gh0u1l5.wechatmagician.xposed.WechatHook
10-02 21:16:35.858 I/Xposed  (  363): Loading modules from /data/app/moe.reimu.weiboxposed-1/base.apk
10-02 21:16:35.879 I/Xposed  (  363):   Loading class moe.reimu.weiboxposed.Module
10-02 21:16:35.901 I/Xposed  (  363): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.CLON-1/base.apk
10-02 21:16:35.928 I/Xposed  (  363):   Loading class com.chelpus.XSupport
10-02 21:16:35.958 I/Xposed  (  363): Loading modules from /data/app/com.phantom.onetapvideodownload-1/base.apk
10-02 21:16:35.984 I/Xposed  (  363):   Loading class com.phantom.onetapvideodownload.hooks.MediaPlayerHook
10-02 21:16:35.993 I/Xposed  (  363):   Loading class com.phantom.onetapvideodownload.hooks.SelfHook
10-02 21:16:35.996 I/Xposed  (  363):   Loading class com.phantom.onetapvideodownload.hooks.WebViewHook
10-02 21:16:35.997 I/Xposed  (  363):   Loading class com.phantom.onetapvideodownload.hooks.ChromeHook
10-02 21:16:35.997 I/Xposed  (  363):   Loading class com.phantom.onetapvideodownload.hooks.MediaMetadataRetriever
10-02 21:16:35.998 I/Xposed  (  363):   Loading class com.phantom.onetapvideodownload.hooks.SoundCloudHook
10-02 21:16:35.999 I/Xposed  (  363):   Loading class com.phantom.onetapyoutubemodule.YoutubeMediaHook
10-02 21:16:36.001 I/Xposed  (  363):   Loading class com.phantom.onetapfacebookmodule.FacebookHook
10-02 21:16:36.002 I/Xposed  (  363):   Loading class com.phantom.onetapfacebookmodule.FacebookLiteHook
10-02 21:18:52.800 I/Xposed  ( 3351): com.tencent.mm loading com.fkzhang.wechatxposed
10-02 21:19:03.029 I/Xposed  ( 3351): 微X模块 1.13_6.23(22,65) 1
10-02 21:19:03.761 I/Xposed  ( 3351): com.fkzhang.wechatxposed (1.13): wechat version 6.5.13(1100)
10-02 21:29:05.367 W/Xposed  ( 8611): Package name for /data/data/com.android.browser/ireader_plugins/plug.jar had to be retrieved via parser

**Comment by kuku982** [comment]
@Gh0u1L5
重启了手机几次了都不得

**Comment by Gh0u1L5** [comment]
@kuku982 乍一看好像没什么问题，你现在长按朋友圈空白处能看到弹出的菜单吗？就是朋友头像下方的那一大块空白处。能弹出菜单的话，我怀疑6.5.13里面数据库或者UI布局有什么变化，我抽空下一个6.5.13试试看。另外顺便麻烦你停用一次微X模块看看有没有变化，不太确定这两个同时运行是否会有影响。

**Comment by kuku982** [comment]
@Gh0u1L5
能弹出菜单，可以截图，就是朋友圈转发功能不能用

**Comment by kuku982** [comment]
现在又可以用了，我关了微x模块的，被@提示就可以了，

**Comment by Gh0u1L5** [comment]
@kuku982 好的，多谢反馈
