### ISSUE TITLE
[feature] 能直接编译成apk吗

### ISSUE THREAD

**Issue by drcege** [Gh0u1L5/WechatMagician#62]
1.  我需要的功能是：

之前也一直折腾刷机 root xposed ，当系统大更新的时候（Android 7 → 8），twrp经常更新不及时，第三方的会有各种问题，导致刷机失败手机变砖。

我这次把手机格式化了才把手机救回来，真是折腾累了😔

 Xposed  最常用的其实就是防撤回这几个功能，能不能不折腾 xposed ，直接编译一个修改版的微信apk～

**Comment by Gh0u1L5** [comment]
年轻人，[VirtualXposed](https://github.com/android-hacker/VirtualXposed)这个项目了解一下，免刷机使用Xposed框架
