### ISSUE TITLE
request朋友圈关键字过滤

### ISSUE THREAD

**Issue by androidcn** [Gh0u1L5/WechatMagician#7]
request朋友圈关键字过滤

**Comment by Gh0u1L5** [comment]
Ummm，是说遇到特定关键字就屏蔽掉吗？

**Comment by androidcn** [comment]
@Gh0u1L5 对的...
有些文章标题...或者普通文字内容

特别是一些微商,胸罩等等...

**Comment by Gh0u1L5** [comment]
哇，我发现你说的这个功能惊人地有用

**Comment by androidcn** [comment]
@Gh0u1L5 别看Google 发布会了
马上开工吧

**Comment by Gh0u1L5** [comment]
我不是，我没有

**Comment by Wallemuse** [comment]
刚刚看到这个模块。感觉像微X。可以@所有人嘛？哈。

**Comment by Gh0u1L5** [comment]
@slb116763814 暂时不行，@所有人这个功能好像是服务器封掉了，没有封的话可以研究一下试试

**Comment by Gh0u1L5** [comment]
@androidcn 新版本里面已加入该功能，issue我先关了？
@slb116763814 我后来查证了一下发现微信并没有封这个功能，以后兴许会试着实现的

**Comment by Wallemuse** [comment]
@Gh0u1L5 哇。不错哟，我目前还在用微X，兴许我以后就换你的插件了。哈哈。by the way.希望你的插件越来越好。
