### ISSUE TITLE
[Feature]聊天置底功能

### ISSUE THREAD

**Issue by Gh0stKnow** [Gh0u1L5/WechatMagician#73]
## 功能请愿模板

1.  我需要的功能是：聊天列表-聊天置底功能

    例子：
场景：与A用户的聊天记录不想随意被朋友看到，但经常需要联系，不能接受隐藏好友繁琐地输密码和开关。
需求：对于不想在聊天列表很容易就被看见的人能否开发一个聊天置底功能，配合微信自带的消息免打扰即可做到来消息不提示但又能随时聊天的效果。
对某人设置后，新消息将在聊天列表的底部显示，开启后该对话无视系统置顶功能。

原型图已给出[滑稽]
<img width="376" alt="2018-10-20 2 16 29" src="https://user-images.githubusercontent.com/17814208/47252179-c5852e00-d472-11e8-9c8e-4dba5669b138.png">

**Comment by skys215** [comment]
我有300个联系人，会话列表也有100多个，照这么设计，你如何快速到达列表底部？
如果你不想被人看到，那隐藏就好了
如果你自己还要用，那也隐藏就好了
如果自己不想看到，那可以放列表底部吧…

**Comment by Gh0stKnow** [comment]
如何到达列表底部…还真是个问题 先关闭

skys215 <notifications@github.com> 于2018年11月29日周四 下午8:03写道：
