### ISSUE TITLE
请教几个 hook 相关的问题

### ISSUE THREAD

**Issue by Blankeer** [Gh0u1L5/WechatMagician#8]
你好,我有几个关于 hook 方面的问题,想要请教.
首先 我说下对 WechatPackage.kt 里 hook 的理解,望指正.

因为 hook 的关键是找到对应的类和函数,微信每个版本混淆后的大部分包名/类名/函数名会不同,为了”消除”这个差异,准备 hook 某个方法时,尽量根据 混淆不会影响的特征 来寻找,主要是以下特征: 固定包名/固定类名/固定函数名/函数特征(参数类型,返回值等)/包含某些固定函数,根据这些找到关键类/函数.

这个思路我觉得很有意思,感觉很强,可以”消除”微信的版本差异,结合我的理解和思考,提出以下问题:
1.如果微信某个版本升级代码大改动,导致很多特征和以前不一样(虽然可能性不大),比如同一个方法升级前后参数和返回值不同,那么这样的 hook 也会挂,如果发生的话,是否只能分版本适配代码?
2.如果我上述的理解没错的话,那么我就要钻空子了,如果存在多个特征相同/接近的类/函数时,该怎么区分呢?举个例子,同一个类里有多个方法 参数 返回值都一样,只是函数名不一样,内部逻辑也不一样,我要 hook 其中某一个,这时我该怎么办?还有没有更深层次的判别方法?

望作者百忙之中能解惑,感谢开源.

**Comment by Gh0u1L5** [comment]
你好，感谢你对Wechat Magician的关注。
1. 如果微信升级大变动的话，插件就只能根据微信版本选择需要的特征了。插件里面早有相关的准备，甚至还有一个类已经用上了，比如这里https://github.com/Gh0u1L5/WechatMagician/blob/2.2.4/src/main/kotlin/com/gh0u1l5/wechatmagician/backend/WechatPackage.kt#L75
2. 这也是我在思考的一个问题，目前我采取的办法仅仅是逆向的时候挑比较刁钻的地方Hook，比如说各个UI类因为方法继承自Android所以没法混淆。但是我脑海里确实有个不太成熟的思路或许可以应对这种情况，那就是分析堆栈。如果某个函数A不好定位的话，就去试试定位它调用到的B、C、D.....函数，然后从Hook住的地方往上翻找栈里的函数。类似的，如果有某个类A'不好定位的话，找一个函数返回类型是A'的，把它的返回类型取下来。总体来说这套比对特征进行定位的办法是自由度相当高的，能不能准确定位到某个类/函数全靠程序员发挥。

**Comment by Blankeer** [comment]
感谢回答!
我会持续关注这个项目的.
另:我也是 Xposed 模块开发者,目前也是在做 wechat 相关的模块.想问下你有没有写过相关的博客,如果没有,有没有考虑过分享经验?方便"后来者".😬

**Comment by Gh0u1L5** [comment]
嘛，博客之类的倒是没写过。主要是我觉得很多时候文字说不明白很多细节，还是对着我的代码直接提问我会比较有效率。
