### ISSUE TITLE
转发单纯的公众号朋友圈会失败

### ISSUE THREAD

**Issue by trivita** [Gh0u1L5/WechatMagician#9]
出现null token or idx

**Comment by Gh0u1L5** [comment]
你是说那种网页链接之类的吧？那个因为转发本来就很简单所以偷懒没有做，大家有需要的话也可以加

**Comment by Gh0u1L5** [comment]
@trivita 新更新的版本里添加了对这种朋友圈的支持，issue我先关了？

**Comment by trivita** [comment]
:ok_hand:
